Docs commit.
This is a hygienic commit in which I cleared-out some old, commented-
out code & updated the docstrings generally. No change in functionality.

diff --git a/infra/cache-test-cluster-up b/infra/cache-test-cluster-up
--- a/infra/cache-test-cluster-up
+++ b/infra/cache-test-cluster-up
@@ -10,9 +10,9 @@ function hc {
         sleep 0.5
         status=$(curl -s http://localhost:${port}/healthcheck)
         ntries=$(($ntries+1))
-        # Give it five seconds
-        if [ ${ntries} -gt 10 ]; then
-            echo "${bin} failed to come up" >&2
+        # Give it ten seconds
+        if [ ${ntries} -gt 20 ]; then
+            echo "${bin}:${port} failed to come up" >&2
             set -e
             return "1"
         fi
