At long last, rename the `indielinks` binary to `indielinksd`.
The commit looks large, but it's just bunch of renamed files &
updated configuration.

diff --git a/infra/indielinks-up b/infra/indielinks-up
--- a/infra/indielinks-up
+++ b/infra/indielinks-up
@@ -4,12 +4,13 @@ if [ $# -ne 1 ]; then
     exit 2
 fi
 config="$1"
+rust_log="debug,aws_config=warn,aws_runtime=info,aws_sdk_sts=info,aws_sigv4=info,aws_smithy_runtime=info,aws_smithy_runtime_api=info,aws_smithy_http_client=info,aws_sdk_dynamodb=info,hyper=info,scylla=info,openraft=info"
 
 set -ex
 here=$(dirname $(realpath $0))
 cd $here/../indielinks
 # Run `indielinks` as a daemon in the indielinks directory
-RUST_BACKTRACE=1 RUST_LOG="debug,aws_config=warn,aws_runtime=info,aws_sdk_sts=info,aws_sigv4=info,aws_smithy_runtime=info,aws_smithy_runtime_api=info,aws_smithy_http_client=info,aws_sdk_dynamodb=info,hyper=info,scylla=info,openraft=info" cargo run --bin indielinks -- -D -p -C -c ${here}/../indielinks-test/${config}
+RUST_BACKTRACE=1 RUST_LOG="${rust_log}" cargo run --bin indielinksd -- -D -p -C -c ${here}/../indielinks-test/${config}
 
 sleep=0.5
 # curl can fail if the server isn't up, yet
@@ -22,7 +23,7 @@ while [ "${status}" != "GOOD" ]; do
     ntries=$(($ntries+1))
     # Give it five seconds
     if [ ${ntries} -gt 10 ]; then
-        echo "indielinks failed to come up" >&2
+        echo "indielinksd failed to come up!" >&2
         exit 1
     fi
 done
