Implement `posts/get`, `posts/delete` and `tags/get`.
This (rather large) patch contains a first implementation of the
`posts/get` and `posts/delete` handlers. I'm unhappy with much
of the implementation of the storage backends, but I've wanted
to have a working integration test suite before I re-factor.

The patch includes a start on the Indielinks metrics framework;
I've used Tolnay's `inventory` crate to support registering
metrics near their use and macros to reduce the boilerplate
involved looking-up the OTel instruments and calling their
various methods.

It also includes a start on integration tests for these two
endpoints, building on the work in the last patch. I've laid-out
the basic structure of the integration tests, the configuration
facility, & so on, and implemented a first "smoke" test for
the del.icio.us API.

diff --git a/infra/scylla-up b/infra/scylla-up
--- a/infra/scylla-up
+++ b/infra/scylla-up
@@ -1,13 +1,23 @@
 #!/usr/bin/env bash
 set -ex
+here=$(dirname $(realpath $0))
+cd $here
 docker compose -f compose.local.yaml up -d
-nnodes=$(docker exec -it scylla-node-1 nodetool status|grep -F UN|wc -l)
+ntries=1
+nnodes=$(docker exec scylla-node-1 nodetool status|grep -F UN|wc -l)
 while [ ${nnodes} -ne 3 ]; do
     sleep 0.5
-    nnodes=$(docker exec -it scylla-node-1 nodetool status|grep -F UN|wc -l)
+    nnodes=$(docker exec scylla-node-1 nodetool status|grep -F UN|wc -l)
+    ntries=$(($ntries+1))
+    # Give it ten seconds
+    if [ ${ntries} -gt 20 ]; then
+        echo "ScyllaDB failed to come up" >&2
+        exit 1
+    fi
 done
 docker cp indielinks.cql scylla-node-1:/indielinks.cql
 docker cp dev-charge.cql scylla-node-1:/dev-charge.cql
+
 docker exec -i scylla-node-1 cqlsh -f /indielinks.cql
 docker exec -i scylla-node-1 cqlsh -f /dev-charge.cql
 RUST_LOG="debug,scylla::transport=debug" cargo run --bin indielinks-ddb -- \
