Accept ActivityPub follows.
This (rather large) patch implements a handler for the
`/users/{username}/inbox` endpoint that handles follow requests
(including sending the accept message back). HTTP request signature
verification & creation are also implemented.

It also adds a script to the `infra` folder, `stunnel-up`. This
will create a TLS endpoint on the localhost at port 443 and
forward the traffic to the local indielink's public endpoint.
It uses a self-signed certificate (also part of this commit).

I've tested against a local Mastodon instance and stood-up a minimal
integration test.

diff --git a/infra/scylla-down b/infra/scylla-down
--- a/infra/scylla-down
+++ b/infra/scylla-down
@@ -3,3 +3,15 @@ set -ex
 here=$(dirname $(realpath $0))
 cd $here
 docker compose -f compose.local.yaml down
+ntries=1
+nnodes=$(docker ps|grep 'scylla-node-*'|wc -l)
+while [ ${nnodes} -ne 0 ]; do
+    sleep 0.5
+    nnodes=$(docker ps|grep 'scylla-node-*'|wc -l)
+    ntries=$(($ntries+1))
+    # Give it ten seconds
+    if [ ${ntries} -gt 20 ]; then
+        echo "ScyllaDB failed to shut down" >&2
+        exit 1
+    fi
+done
